/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 06/04/2019 00:26:44
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            37000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI48_VALUE                          48000000
#define MX_MSI_VALUE                            2097000
#define MX_PLLCLKFreq_Value                     24000000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       16000000
#define MX_FCLKCortexFreq_Value                 16000000
#define MX_AHBFreq_Value                        16000000
#define MX_APB1Freq_Value                       16000000
#define MX_APB2Freq_Value                       16000000
#define MX_48CLKFreq_Value                      24000000
#define MX_48RNGFreq_Value                      24000000
#define MX_48USBFreq_Value                      24000000
#define MX_ADCFreq_Value                        16000000
#define MX_I2C1Freq_Value                       16000000
#define MX_LCDFreq_Value                        32000
#define MX_LPUARTFreq_Value                     16000000
#define MX_LPTIMFreq_Value                      16000000
#define MX_PWRFreq_Value                        16000000
#define MX_USART1Freq_Value                     2097000
#define MX_USART2Freq_Value                     16000000
#define MX_RTCFreq_Value                        37000
#define MX_RTCHSEDivFreq_Value                  4000000
#define MX_TimerFreq_Value                      16000000
#define MX_VCOOutputFreq_Value                  48000000
#define MX_WatchDogFreq_Value                   37000

/*-------------------------------- CRC        --------------------------------*/

#define MX_CRC                                  1

/* GPIO Configuration */

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PA9 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PA9
#define MX_I2C1_SCL_GPIOx                       GPIOA
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF1_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PA10 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PA10
#define MX_I2C1_SDA_GPIOx                       GPIOA
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_10
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF1_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* NVIC Configuration */

/* NVIC I2C1_IRQn */
#define MX_I2C1_IRQn_interruptPremptionPriority 0
#define MX_I2C1_IRQn_Subriority                 0

/*-------------------------------- IWDG       --------------------------------*/

#define MX_IWDG                                 1

/* GPIO Configuration */

/*-------------------------------- LPUART1    --------------------------------*/

#define MX_LPUART1                              1

/* GPIO Configuration */

/* Pin PA0-CK_IN */
#define MX_LPUART1_RX_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_LPUART1_RX_Pin                       PA0_CK_IN
#define MX_LPUART1_RX_GPIOx                     GPIOA
#define MX_LPUART1_RX_GPIO_PuPd                 GPIO_NOPULL
#define MX_LPUART1_RX_GPIO_Pin                  GPIO_PIN_0
#define MX_LPUART1_RX_GPIO_AF                   GPIO_AF6_LPUART1
#define MX_LPUART1_RX_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PA1 */
#define MX_LPUART1_TX_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_LPUART1_TX_Pin                       PA1
#define MX_LPUART1_TX_GPIOx                     GPIOA
#define MX_LPUART1_TX_GPIO_PuPd                 GPIO_NOPULL
#define MX_LPUART1_TX_GPIO_Pin                  GPIO_PIN_1
#define MX_LPUART1_TX_GPIO_AF                   GPIO_AF6_LPUART1
#define MX_LPUART1_TX_GPIO_Mode                 GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC LPUART1_IRQn */
#define MX_LPUART1_IRQn_interruptPremptionPriority 0
#define MX_LPUART1_IRQn_Subriority              0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_SWDIO_Pin                        PA13

/* Pin PA14 */
#define MX_SYS_SWCLK_Pin                        PA14

/*-------------------------------- WWDG       --------------------------------*/

#define MX_WWDG                                 1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_PA4_Pin                              PA4
#define MX_PA4_GPIOx                            GPIOA
#define MX_PA4_GPIO_PuPd                        GPIO_NOPULL
#define MX_BASS_UP                              PA4
#define MX_PA4_GPIO_Pin                         GPIO_PIN_4
#define MX_PA4_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PC15-OSC32_OUT */
#define MX_PC15_OSC32_OUT_Pin                   PC15_OSC32_OUT
#define MX_PC15_OSC32_OUT_GPIOx                 GPIOC
#define MX_PC15_OSC32_OUT_GPIO_PuPd             GPIO_PULLUP
#define MX_MFB                                  PC15_OSC32_OUT
#define MX_PC15_OSC32_OUT_GPIO_Pin              GPIO_PIN_15
#define MX_PC15_OSC32_OUT_GPIO_ModeDefaultEXTI  GPIO_MODE_IT_FALLING

/* Pin PA7 */
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_GPIO_PuPd                        GPIO_NOPULL
#define MX_BASS_DN                              PA7
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PC14-OSC32_IN */
#define MX_PC14_OSC32_IN_GPIO_Speed             GPIO_SPEED_FREQ_LOW
#define MX_PC14_OSC32_IN_Pin                    PC14_OSC32_IN
#define MX_PC14_OSC32_IN_GPIOx                  GPIOC
#define MX_PC14_OSC32_IN_PinState               GPIO_PIN_SET
#define MX_PC14_OSC32_IN_GPIO_PuPd              GPIO_PULLDOWN
#define MX_AMP_EN                               PC14_OSC32_IN
#define MX_PC14_OSC32_IN_GPIO_Pin               GPIO_PIN_14
#define MX_PC14_OSC32_IN_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PB9-BOOT0 */
#define MX_PB9_BOOT0_Pin                        PB9_BOOT0
#define MX_PB9_BOOT0_GPIOx                      GPIOB
#define MX_PB9_BOOT0_GPIO_PuPd                  GPIO_NOPULL
#define MX_INT                                  PB9_BOOT0
#define MX_PB9_BOOT0_GPIO_Pin                   GPIO_PIN_9
#define MX_PB9_BOOT0_GPIO_Mode                  GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */
